* bonjourmadame.el

Display the image from bonjourmadame.fr within GNU/Emacs.

** Disclamer

For certain person, the image displayed might be NSFW.

** Install

/Soon available on Melpa/

** Usage

- =M-x bonjourmadame=
- =M-x bonjourmadame-browse=

** How it works

After launching the command =M-x bonjourmadame= it opens a new buffer and insert the image.

Images are stored locally in the =~/.bonjourmadame/= directory. You might want to remove or empty it regularly in order not to get caught or to save space.

As images are updated at 10AM (Europe/Paris timezone), it looks at the current time. Therefore, if you launch the command before 10AM, you will have the image of yesterday. Be patient and wait 10AM to get the new one.

** Keys

Once in the =*Bonjour Madame*= buffer, you can hit:

- =n= to get the next image
- =p= to get the previous image
- =h= to hide the buffer (switch to the previous one)
- =q= to quit (kill the buffer)

** Changelog

- v0.3: add page navigation
- v0.2: make it a major mode
- v0.1: first release
